export const hotelTypes: string[] = [
  "Resort",
  "Boutique Hotel",
  "Hostel",
  "Bed and Breakfast",
  "Guesthouse",
  "Motel",
  "Luxury Hotel",
  "Business Hotel",
  "Airport Hotel",
  "Serviced Apartment",
  "Eco Hotel",
  "Villa",
  "Cottage",
  "Capsule Hotel",
  "Extended Stay Hotel",
  "Budget Hotel",
  "Inn",
];

export const hotelFacilities: string[] = [
  "Free Wi-Fi",
  "Swimming Pool",
  "Gym",
  "Spa",
  "Restaurant",
  "Bar",
  "Parking",
  "Airport Shuttle",
  "Pet-Friendly",
  "Laundry Service",
  "Room Service",
  "24-Hour Front Desk",
  "Air Conditioning",
  "Conference Rooms",
  "Business Center",
  "Non-Smoking Rooms",
  "Wheelchair Accessible",
  "Breakfast Included",
  "Childcare Services",
  "Fitness Center",
  "Beach Access",
  "Golf Course",
  "Sauna",
  "Hot Tub",
  "Entertainment Room",
  "Bicycle Rental",
  "Tennis Court",
  "Car Rental Service",
  "Massage Services",
  "Concierge Service",
];
